# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6e966c578a2ec06bfda1221ecceff4080ce1c4e5cbe3ed71b789a3ea3dacc56d181f756e43e249823c5d24afc1e1c03c6dd77d3a05e4ed7bb4536a479da1531

test:
  secret_key_base: 5e6af9c257f858ba9aad7efa99f414c11e056b1be29d39604d1a3e8e65f3607b39612b793ef6e8cce4dd02e8851ca1d739e7f95c44ae8fb0f7dcfc59df31d4ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
